<?php

namespace AppBundle\Repository;

/**
 * InvoiceRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class InvoiceRepository extends \Doctrine\ORM\EntityRepository
{
    public function findByAuthor($userId){

        return $this->getEntityManager()
            ->createQueryBuilder()
            ->select('i')
            ->from('AppBundle:Invoice', 'i')
            ->leftJoin('i.user','u')
            ->leftJoin('i.booking', 'b')
            ->where('u.id =:uid')
            ->setParameter('uid', $userId)
            ->getQuery()->getResult();
    }

    public function findUniqByAuthorAndId($userId, $id){

        return $this->getEntityManager()
            ->createQueryBuilder()
            ->select('i')
            ->from('AppBundle:Invoice', 'i')
            ->leftJoin('i.user','u')
            ->leftJoin('i.booking', 'b')
            ->where('i.id =:id')
            ->andWhere('u.id =:uid')
            ->setParameter('id', $id)
            ->setParameter('uid', $userId)
            ->getQuery()->getOneOrNullResult();
    }
}
