<?php

namespace AppBundle\Repository;

/**
 * MenuRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class MenuRepository extends \Doctrine\ORM\EntityRepository
{
    public function findMenus(){
        return $this->getEntityManager()
            ->createQueryBuilder()
            ->select('m.name, m.slug, m.metaTitle, m.metaDescription')
            ->from('AppBundle:Menu', 'm')
            ->where('m.status = :st')
            ->orderBy('m.position', 'ASC')
            ->setParameter('st', 1)
            ->getQuery()->getResult();

    }
}
