<?php

namespace AppBundle\Repository;

/**
 * MenuItomRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class MenuItomRepository extends \Doctrine\ORM\EntityRepository
{
}
