<?php

namespace AppBundle\Repository;

/**
 * ProductRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ProductRepository extends \Doctrine\ORM\EntityRepository
{

    public function fidListing(){
        $q = $this->getEntityManager()->createQueryBuilder()
            ->select('p, pi')
            ->from('AppBundle:Product', 'p')
            ->innerJoin('p.productItem', 'pi')
//            ->leftJoin('p.category', 'c')
            ->where('p.id is not null')
            ->orderBy('p.updated', 'DESC')
            ;

        return $q->getQuery()->getResult();
    }
}
