<?php

namespace AppBundle\Repository;

/**
 * ProductIngridientRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ProductItemRepository extends \Doctrine\ORM\EntityRepository
{
}
