<?php

namespace AppBundle\Repository;

/**
 * ProductStorageRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ProductStorageRepository extends \Doctrine\ORM\EntityRepository
{

    /**
     * This function use to get product store info by product
     *
     * @param $prodId
     * @return \Doctrine\ORM\QueryBuilder
     */
    public function findStoreByProduct($prodId){

        return $this->getEntityManager()
            ->createQueryBuilder()
            ->select('ps')
            ->from('AppBundle:ProductStorage', 'ps')
            ->innerJoin('ps.product', 'pr')
            ->where('pr.id = :pId')
            ->andWhere('ps.count > 0')
            ->andWhere('ps.lot IS NOT NULL AND ps.expiryDate is not null and ps.supDate is not null')
            ->orderBy('ps.expiryDate', 'ASC')
            ->setParameter('pId', $prodId)
            ->getQuery()->getResult()
            ;
    }

}
