<?php

namespace AppBundle\Repository;

/**
 * UserEmailsRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class UserEmailsRepository extends \Doctrine\ORM\EntityRepository
{

}
