<?php

namespace AppBundle\Repository;

/**
 * UserPriceRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class UserPriceRepository extends \Doctrine\ORM\EntityRepository
{
}
