# Learn more about services, parameters and containers at
# http://symfony.com/doc/current/book/service_container.html
parameters:
#    parameter_name: value

services:
#    service_name:
#        class: AppBundle\Directory\ClassName
#        arguments: ["@another_service_name", "plain_value", "%parameter_name%"]

    app.form.type.gender:
            class: AppBundle\Form\IconType
            tags:
                - { name: form.type, alias: ad_file_type }

    app.form.registration:
            class: AppBundle\Form\RegistrationType
            tags:
                - { name: form.type, alias: app_user_registration }

  # Admin
    app.admin.user:
            class: AppBundle\Admin\UserAdmin
            arguments: [~, AppBundle\Entity\User, SonataAdminBundle:CRUD]
            tags:
                - {name: sonata.admin, manager_type: orm, group: User, label: User}

    admin.products.item:
        class: AppBundle\Admin\ProductItemAdmin
        arguments: [~, AppBundle\Entity\ProductItem, ~]
        tags:
            - {name: sonata.admin, manager_type: orm, group: Product, label: Product Item, show_in_dashboard: true}

    admin.product:
        class: AppBundle\Admin\ProductAdmin
        arguments: [~, AppBundle\Entity\Product, ~]
        tags:
            - {name: sonata.admin, manager_type: orm, group: Product, label: Product, show_in_dashboard: true}

    admin.invoice:
        class: AppBundle\Admin\InvoiceAdmin
        arguments: [~, AppBundle\Entity\Invoice, ~]
        tags:
            - {name: sonata.admin, manager_type: orm, group: Invoice, label: Invoices, show_in_dashboard: true}

    admin.invoice_settings:
        class: AppBundle\Admin\InvoiceSettingsAdmin
        arguments: [~, AppBundle\Entity\InvoiceSettings, ~]
        tags:
            - {name: sonata.admin, manager_type: orm, group: Invoice, label: Invoice Settings, show_in_dashboard: true}

    admin.menues:
        class: AppBundle\Admin\MenuAdmin
        arguments: [~, AppBundle\Entity\Menu, ~]
        tags:
            - {name: sonata.admin, manager_type: orm, group: Template, label: Menu, show_in_dashboard: true}

    admin.menue_itom:
        class: AppBundle\Admin\MenuItomAdmin
        arguments: [~, AppBundle\Entity\MenuItom, ~]
        tags:
            - {name: sonata.admin, manager_type: orm, group: Template, label: Menu Item, show_in_dashboard: true}

    admin.manufacturer:
        class: AppBundle\Admin\ManufacturerAdmin
        arguments: [~, AppBundle\Entity\Manufacturer, ~]
        tags:
            - {name: sonata.admin, manager_type: orm, group: Product, label: Manufacturer, show_in_dashboard: true}

    admin.booking:
        class: AppBundle\Admin\BookingAdmin
        arguments: [~, AppBundle\Entity\Booking, ~]
        tags:
            - {name: sonata.admin, manager_type: orm, group: Invoice, label: Booking, show_in_dashboard: true}

    admin.user_settings:
        class: AppBundle\Admin\UserSettingsAdmin
        arguments: [~, AppBundle\Entity\UserSettings, ~]
        tags:
            - {name: sonata.admin, manager_type: orm, group: User, label: Credit Application, show_in_dashboard: true}

